### ISSUE TITLE
Using this.context is causing me errors

### ISSUE THREAD

**Issue by elie222** [thomascarvalho/gatsby-plugin-mixpanel#1]
I've tried using `this.context` as suggested in the docs, but it throws an undefined error.

**Comment by elie222** [comment]
To be more precise. The `context` object is  an empty object and doesn't have the `mixpanel` property on it.

**Comment by thomascarvalho** [comment]
I can't reproduce this problem. Did you correctly declare `mixpanel` as contextTypes ?

```
import React from 'react'
import PropTypes from 'prop-types'

class Hello extends React.Component {
  render() {
    console.log(this.context);
    return <h1>Hello</h1>;
  }
}

Hello.contextTypes = {
  mixpanel: PropTypes.object.isRequired
}

```

**Comment by elie222** [comment]
Thanks. The contextTypes solved my issue. Sorry for the trouble and thanks
for the help.
