### ISSUE TITLE
Allow `api_host` or any other param in config

### ISSUE THREAD

**Issue by dimitrisnl** [thomascarvalho/gatsby-plugin-mixpanel#10]
https://github.com/thomascarvalho/gatsby-plugin-mixpanel/blob/a7310256805762bea1ddc84062d5a94234e930f8/src/gatsby-browser.js#L55

Here we could also pass any other initialization param, like the option to use a different host (api_host).

**Comment by thomascarvalho** [comment]
Hi @dimitrisnl, I just made a new release of the plugin (v3.0.0), you can override the default configuration of the library mixpanel.

`{
    resolve: 'gatsby-plugin-mixpanel',
    options: {
      apiToken: 'YOUR_MIXPANEL_API_TOKEN',
      mixpanelConfig: {
        'api_host': 'XXXX'
      }, // you can override default config for mixpanel library https://github.com/mixpanel/mixpanel-js/blob/8b2e1f7b/src/mixpanel-core.js#L87-L110
    },
  },`

Also the plugin now uses the new version of the context API and the React hooks.

The readme has been updated, tell me if you have problems with this new version.

**Comment by dimitrisnl** [comment]
That's fantastic @thomascarvalho , thank you very much!
