### ISSUE TITLE
Build error while setting mixpanelConfig

### ISSUE THREAD

**Issue by dimitrisnl** [thomascarvalho/gatsby-plugin-mixpanel#11]
I'm trying out how `loaded` hook works with the library.

```js
{
  resolve: `gatsby-plugin-mixpanel`,
  options: {
    apiToken: process.env.MIXPANEL_KEY || ' ',
    mixpanelConfig: {
      loaded: function(mixpanel) {
        mixpanel.register_once({
          'First Page Visit': new Date().toISOString(),
        });
      },
    },
  },
},
```

but during build it fails with

```
 4951 |  */
  4952 | MixpanelLib.prototype.get_config = function(prop_name) {
> 4953 |     return this['config'][prop_name];
       | ^
  4954 | };
  4955 | 
  4956 | /**


  WebpackError: TypeError: Cannot read   property 'name' of undefined
  
  - mixpanel.cjs.js:4953 MixpanelLib..    /node_modules/mixpanel-browser/bui    ld/mixpanel.cjs.js.MixpanelLib.get    _config
    [lib]/[mixpanel-browser]/build/mix    panel.cjs.js:4953:1
  
  - mixpanel.cjs.js:4979 MixpanelLib..    /node_modules/mixpanel-browser/bui    ld/mixpanel.cjs.js.MixpanelLib.toS    tring
    [lib]/[mixpanel-browser]/build/mix    panel.cjs.js:4979:1
```

**Comment by dimitrisnl** [comment]
During some more testing, it doesn't happen when I pass `mixpanelConfig`, but when I wrap a component with `withMixpanel`. In development mode the same snippets work. Trying to identify the problem.

**Comment by dimitrisnl** [comment]
Strangely I can override some configuration, but the loaded function hasn't changed

![Screen Shot 2019-06-17 at 1 23 38 PM](https://user-images.githubusercontent.com/4951004/59597710-27ca2780-9103-11e9-9274-964180467112.png)

**Comment by dimitrisnl** [comment]
Update:

The build error was an implementation error of mine. I would love to identify how to properly call the `loaded` hook though. @thomascarvalho

**Comment by thomascarvalho** [comment]
Hi @dimitrisnl I looked for why I can't do it either, in fact in the documentation of gatsby plugins ( [using-a-plugin-in-your-site](https://www.gatsbyjs.org/docs/using-a-plugin-in-your-site/) ) it is indicated that 

>  plugin options will be stringified by Gatsby, so they cannot be functions.

Sorry but you can't override the mixpanel loaded function 😢
