### ISSUE TITLE
Support React 18

### ISSUE THREAD

**Issue by brendanator** [thomascarvalho/gatsby-plugin-mixpanel#40]
This plugin is great, but it's stopping me upgrade to React 18, please could you update the peer dependencies

*Edited to only mention React 18, not Gatsby 4*

**Comment by jonaswide** [comment]
#42 Pull request created

**Comment by thomascarvalho** [comment]
Thx @jonaswide for the PR.

@brendanator it should be ok with the latest version

**Comment by brendanator** [comment]
Thank you @jonaswide and @thomascarvalho 🙏
