### ISSUE TITLE
npm package description error (?)

### ISSUE THREAD

**Issue by Nosferatu31** [thomascarvalho/gatsby-plugin-mixpanel#46]
@thomascarvalho 

In GitHub repo it says `v2 & v3 & v4`, in [npm page](https://www.npmjs.com/package/gatsby-plugin-mixpanel) it says `v2 & v3`.
Is this a typo or is there any compatibility issues with Gatsby v4?

**Comment by thomascarvalho** [comment]
Yes it's just a typo, I just changed the readme recently.

It's also working for v4
