### ISSUE TITLE
Gatsby v5 support

### ISSUE THREAD

**Issue by jfgilmore** [thomascarvalho/gatsby-plugin-mixpanel#49]
Hi, just wondering if this will be updated to support version 5 of Gatsby?

**Comment by aaadamgo** [comment]
Still waiting on this as well, it produces a build error when trying to use it in v5. Need a solution!

**Comment by thomascarvalho** [comment]
Hi, sorry for the very late reply I hadn't seen the original question.
Not having used gatsby recently, I need to take some time to update the plugin.
I'll watch it over the next few days.

**Comment by h0t-p1xels** [comment]
I'm also hoping to get mixpanel working with Gatsby v5. 🤞

I've tried adding the package without using the plugin and am getting ```ERROR #98123  WEBPACK.BUILD-HTML Generating SSR bundle failed``` errors which I am having no luck fixing. 😢

Has anyone got Gatsby v5 to work with Mixpanel without using the plugin?
Or any ideas when the plugin might be able to be updated?

Thank you so much for any help anyone can offer. 🙏

**Comment by thomascarvalho** [comment]
Hey here !

I have just released a new version of the plugin (v4.1.0) that supports gatsby v5.
I tested it seems to work but let me know if you encounter any problems.

**Comment by h0t-p1xels** [comment]
Thank you so much for this! 😄
