### ISSUE TITLE
Allow auto tracking on route change

### ISSUE THREAD

**Issue by dimitrisnl** [thomascarvalho/gatsby-plugin-mixpanel#6]
```
exports.onRouteUpdate = ({ location }, pluginOptions) => {
  const options = getOptions(pluginOptions);

  if (!isEnable(options)) {
    return;
  }

  if (options.pageViews) {
    const mixpanelEvent = options.pageViews[location.pathname];
    if (mixpanelEvent) {
      mixpanel.track(mixpanelEvent, location);
    }
  }
};
```

How about something like

if pageViews is array
	check if current route should be tracked
if pageViews is set to `all`
	track

Currently I have to whitelist 15+ pages.

**Comment by thomascarvalho** [comment]
Yes it's a good idea, I'll add the option `pageViews: 'all'` in the next release.

**Comment by dimitrisnl** [comment]
@thomascarvalho 	Thank you for considering it!

I closed it earlier, since I could do the same thing, using context in the Layout wrapper of every page.

But it's a nice addition for my next projects.

👍 	👍
