### ISSUE TITLE
Plugin does not work on my site

### ISSUE THREAD

**Issue by Emaasit** [thomascarvalho/gatsby-plugin-mixpanel#7]
I have tried this plugin for two weeks now but for some reason, mixpanel UI says that mixpanle has not been installed on my Gatsby website ([https://www.danielemaasit.com/](https://www.danielemaasit.com/)). I followed the install-instructions to the letter but I can't figure out what's wrong. It's driving me crazy. I installed other related npm packages like `react-mixpanel`, `mixpanel-browser` as well, hoping this would solve it but it doesn't. Please help. My config looks like this:
```
{
      resolve: 'gatsby-plugin-mixpanel',
      options: {
        apiToken: config.mixpanelAPIToken, // required
        // optional fields, default values
        // debug: false, // if true activate debug mode on mixpanel library
        // enableOnDevMode: true, // if false mixpanel will be activated on NODE_ENV=production only
        // pageViews: null, //
      },
    }
```

My mixpanel Token is saved in a `config.js` file.

**Comment by thomascarvalho** [comment]
Hello Daniel, going to your site we can see (in developper tools) that the mixpanel library is properly loaded and makes many calls.

I think the problem has to come from elsewhere, do you have some error messages somewhere ?
Is it the right API token?
